# Generated by Django 5.2.7 on 2025-11-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_password',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
