# Generated by Django 5.2.7 on 2025-11-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supermarket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.supermarket'),
            preserve_default=False,
        ),
    ]
