# Generated by Django 5.2.7 on 2025-11-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('simple', 'SIMPLE'), ('lux', 'LUX')], max_length=10, null=True),
        ),
    ]
